export interface Link {
  rel: string;
  href: string;
}

export interface RefObject {
  links?: Link[];
  id: string;
  refName: string;
}

export interface AddressBookAddress {
  links?: Link[];
  addr1?: string;
  addressee?: string;
  addrText?: string;
  attention?: string;
  city?: string;
  country?: RefObject;
  custrecord_av_after_placeholder?: string;
  custrecord_av_before_placeholder?: string;
  custrecord_av_valid_status?: RefObject;
  override?: boolean;
  zip?: string;
  state?: string;
}

export interface AddressBookItem {
  links?: Link[];
  addressBookAddress?: AddressBookAddress;
  addressBookAddress_text?: string;
  addressId?: string;
  defaultBilling?: boolean;
  defaultShipping?: boolean;
  id?: number;
  internalId?: number;
  label?: string;
}

export interface AddressBook {
  links?: Link[];
  items?: AddressBookItem[];
  totalResults?: number;
}

export interface ContactList {
  links?: Link[];
  count?: number;
  hasMore?: boolean;
  items?: any[];
  offset?: number;
  totalResults?: number;
}

export interface CurrencyListItem {
  links?: Link[];
  balance?: number;
  currency?: RefObject;
  prepaymentBalance?: number;
  unbilledOrders?: number;
}

export interface CurrencyList {
  links?: Link[];
  items?: CurrencyListItem[];
  totalResults?: number;
}

export interface TaxRegistrationItem {
  links?: Link[];
  id?: number;
  nexus?: RefObject;
  nexusCountry?: RefObject;
  taxRegistrationNumber?: string;
}

export interface TaxRegistration {
  links?: Link[];
  items?: TaxRegistrationItem[];
  totalResults?: number;
}

export interface VendorData {
  links?: Link[];
  addressBook?: AddressBook;
  balance?: number;
  balancePrimary?: number;
  category?: RefObject;
  companyName?: string;
  contactList?: ContactList;
  cseg_co_thirdparty?: RefObject;
  currency?: RefObject;
  currencyList?: CurrencyList;
  custentity_11724_pay_bank_fees?: boolean;
  custentity_2663_payment_method?: boolean;
  custentity_ad_cl_economic_activity?: ContactList;
  custentity_ad_gl_customform?: string;
  custentity_ad_gl_vat_reg_num?: string;
  custentity_co_document_type?: RefObject;
  custentity_co_identification_num?: string;
  custentity_co_invoicing_email?: string;
  custentity_co_minor_quantity_entity?: boolean;
  custentity_co_nature?: RefObject;
  custentity_co_tax_regime?: RefObject;
  custentity_co_tax_schema?: RefObject;
  custentity_co_taxresponsibilities?: ContactList;
  custentity_edoc_gen_trans_pdf?: boolean;
  custentity_edoc_use_sender_list?: boolean;
  custentity_fte_entity_l_taxregime?: RefObject;
  custentity_psg_ei_auto_select_temp_sm?: boolean;
  custentity_psg_ei_entity_edoc_standard?: RefObject;
  customForm?: RefObject;
  dateCreated?: string;
  defaultAddress?: string;
  defaultTaxReg?: string;
  defaultVendorPaymentAccount?: RefObject;
  email?: string;
  emailPreference?: RefObject;
  emailTransactions?: boolean;
  entityId?: string;
  faxTransactions?: boolean;
  id: string;
  isAutogeneratedRepresentingEntity?: boolean;
  isInactive?: boolean;
  isJobResourceVend?: boolean;
  isPerson?: boolean;
  lastModifiedDate?: string;
  legalName?: string;
  payablesAccount?: RefObject;
  prepaymentBalance?: number;
  printTransactions?: boolean;
  subsidiary?: RefObject;
  subsidiaryEdition?: string;
  taxRegistration?: TaxRegistration;
  terms?: RefObject;
  unbilledOrders?: number;
  unbilledOrdersPrimary?: number;
}

export interface VendorResponse {
  status: number;
  software: string;
  data: VendorData;
}

export interface VendorListItem {
  id: string;
  entityId?: string;
  companyName?: string;
  email?: string;
  isInactive?: boolean;
}