name: Deploy Supabase Migrations and Functions

on:
  workflow_dispatch:
    inputs:
      environment:
        description: Environment to deploy
        type: environment

jobs:
  deploy:
    runs-on: ubuntu-latest
    environment: ${{ github.event.inputs.environment }}

    steps:
      - name: Checkout código
        uses: actions/checkout@v3

      - name: Autenticarse en Supabase CLI
        run: |
          npx supabase@2.40.2 login --token "${{ secrets.SUPABASE_ACCESS_TOKEN }}"

      - name: Link al proyecto Supabase
        run: |
          npx supabase@2.40.2 link --project-ref ${{ secrets.SUPABASE_PROJECT_REF }} --password "${{ secrets.SUPABASE_DB_PASSWORD }}"

      - name: Aplicar migraciones al proyecto Supabase
        run: |
          npx supabase@2.40.2 db push --linked

      - name: Deploy de funciones
        run: |
          npx supabase@2.40.2 functions deploy --project-ref ${{ secrets.SUPABASE_PROJECT_REF }}
